version: "3.5"

services:
  super-ebay:
    image: mysql:5.7
    restart: always
    volumes: 
      - ./src/main/resources/dumpDb.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=gui123
      - MYSQL_DATABASE=superebay
      - MYSQL_USER=guilherme
      - MYSQL_PASSWORD=gui123
    expose: 
    - 3306

  app:
    build: .
    depends_on:
      - super-ebay
    ports: 
      - 8081:8080
      - 443:443
    environment:
      - DATABASE_HOST=super-ebay
      - DATABASE_USER=guilherme
      - DATABASE_NAME=superebay
      - DATABASE_PASSWORD=gui123
      - DATABASE_PORT=3306
